services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: system
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    container_name: zipkin_container
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - postgres
      - microservices-network
    restart: unless-stopped

  configms:
    container_name: configms_container
    image: shanmukh01/configms
    depends_on:
      - servicereg
    ports:
      - "8888:8888"
    networks:
      - postgres
      - microservices-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servicereg:8761/eureka/
    restart: unless-stopped

  gatewayms:
    container_name: gatewayms_container
    image: shanmukh01/gatewayms
    ports:
      - "8080:8084"
    networks:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servicereg:8761/eureka/
    restart: unless-stopped

  companyms:
    container_name: companyms_container
    image: shanmukh01/companyms
    ports:
      - "8081:8081"
    depends_on:
      - servicereg
      - configms
    networks:
      - postgres
      - microservices-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped

  jobms:
    container_name: jobms_container
    image: shanmukh01/jobms
    ports:
      - "8082:8082"
    depends_on:
      - servicereg
      - configms
    networks:
      - postgres
      - microservices-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servicereg:8761/eureka/
    restart: unless-stopped

  reviewms:
    container_name: reviewms_container
    image: shanmukh01/reviewms
    ports:
      - "8083:8083"
    depends_on:
      - servicereg
      - configms
    networks:
      - postgres
      - microservices-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped

  servicereg:
    container_name: servicereg
    image: shanmukh01/servicereg
    ports:
      - "8761:8761"
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - postgres
      - microservices-network
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - postgres
      - microservices-network
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
  microservices-network:
    driver: bridge
volumes:
  postgres_data:
  pgadmin_data:
